version: '3.9'

services:
  java_app:
    container_name: java_app
    image: docker-example-envvar:latest
    ports:
      - 9096:9096
    environment:
      - MYSQL_HOST=java_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test

